### PR TITLE
fix: Property 'subscribe' does not exist on type 'AxiosObservable'

### PR DESCRIPTION
**Pull request by songhuige**
This type failed to compile in Typescript4.1.6

### CODE REVIEW

**Review by zhaosiyang — COMMENTED** [review]
@songhuige Thanks for your PR
